/**
 * Technical SEO Audit Configuration
 * 
 * Comprehensive configuration for technical SEO auditing, issue identification, and recommendations
 * Includes audit categories, issues, fixes, and best practices
 */

export const technicalSeoAuditConfig = {
  // Technical SEO Issue Categories (8 categories)
  issueCategories: [
    {
      id: 'crawlability',
      name: 'Crawlability',
      description: 'Issues that prevent search engines from crawling your site',
      severity: 'critical',
      impact: 'High - Prevents indexation',
    },
    {
      id: 'indexation',
      name: 'Indexation',
      description: 'Issues that prevent pages from being indexed',
      severity: 'critical',
      impact: 'High - Reduces visibility',
    },
    {
      id: 'siteStructure',
      name: 'Site Structure',
      description: 'Issues with site architecture and organization',
      severity: 'high',
      impact: 'Medium - Affects crawl efficiency',
    },
    {
      id: 'performance',
      name: 'Performance',
      description: 'Issues affecting page speed and performance',
      severity: 'high',
      impact: 'Medium - Affects rankings',
    },
    {
      id: 'mobileUsability',
      name: 'Mobile Usability',
      description: 'Issues affecting mobile user experience',
      severity: 'high',
      impact: 'High - Mobile-first indexing',
    },
    {
      id: 'security',
      name: 'Security',
      description: 'Security and HTTPS issues',
      severity: 'high',
      impact: 'Medium - Trust and rankings',
    },
    {
      id: 'markup',
      name: 'Structured Data Markup',
      description: 'Issues with schema markup and structured data',
      severity: 'medium',
      impact: 'Low - Affects rich results',
    },
    {
      id: 'redirects',
      name: 'Redirects & URLs',
      description: 'Issues with redirects, URL structure, and canonicalization',
      severity: 'medium',
      impact: 'Medium - Affects crawl efficiency',
    },
  ],

  // Technical SEO Issues (30+ issues)
  technicalIssues: [
    // Crawlability Issues
    {
      id: 'robotsTxtBlocking',
      name: 'Robots.txt Blocking',
      category: 'crawlability',
      severity: 'critical',
      description: 'Important pages blocked by robots.txt',
      impact: 'Prevents crawling of important pages',
      fix: 'Review and update robots.txt to allow crawling',
      priority: 'immediate',
    },
    {
      id: 'noindexTag',
      name: 'Noindex Tag',
      category: 'crawlability',
      severity: 'critical',
      description: 'Pages with noindex meta tag',
      impact: 'Prevents indexation of pages',
      fix: 'Remove noindex tag from pages that should be indexed',
      priority: 'immediate',
    },
    {
      id: 'nofolowLinks',
      name: 'Excessive Nofollow Links',
      category: 'crawlability',
      severity: 'high',
      description: 'Too many nofollow links preventing crawl flow',
      impact: 'Reduces crawl efficiency',
      fix: 'Use nofollow strategically only for untrusted content',
      priority: 'high',
    },
    {
      id: 'crawlErrors',
      name: 'Crawl Errors',
      category: 'crawlability',
      severity: 'high',
      description: 'Pages returning 4xx or 5xx errors',
      impact: 'Prevents crawling and indexation',
      fix: 'Fix server errors and broken pages',
      priority: 'high',
    },
    {
      id: 'blockingResources',
      name: 'Blocking Resources',
      category: 'crawlability',
      severity: 'high',
      description: 'CSS, JavaScript, or images blocked by robots.txt',
      impact: 'Prevents proper rendering',
      fix: 'Allow CSS, JS, and image resources in robots.txt',
      priority: 'high',
    },

    // Indexation Issues
    {
      id: 'duplicateContent',
      name: 'Duplicate Content',
      category: 'indexation',
      severity: 'critical',
      description: 'Duplicate content across multiple URLs',
      impact: 'Dilutes link equity and confuses search engines',
      fix: 'Use canonical tags or consolidate duplicate content',
      priority: 'immediate',
    },
    {
      id: 'thinContent',
      name: 'Thin Content',
      category: 'indexation',
      severity: 'high',
      description: 'Pages with very little content',
      impact: 'Low quality pages may not rank',
      fix: 'Add substantial, unique content to pages',
      priority: 'high',
    },
    {
      id: 'missingCanonical',
      name: 'Missing Canonical Tags',
      category: 'indexation',
      severity: 'high',
      description: 'Pages without canonical tags',
      impact: 'May cause duplicate content issues',
      fix: 'Add canonical tags to all pages',
      priority: 'high',
    },
    {
      id: 'parameterizedUrls',
      name: 'Parameterized URLs',
      category: 'indexation',
      severity: 'medium',
      description: 'Multiple URLs with same content (parameters)',
      impact: 'Creates duplicate content',
      fix: 'Use canonical tags or URL parameters in GSC',
      priority: 'medium',
    },
    {
      id: 'softErrors',
      name: 'Soft 404 Errors',
      category: 'indexation',
      severity: 'medium',
      description: 'Pages returning 200 but with no content',
      impact: 'Wastes crawl budget',
      fix: 'Return proper 404 status for non-existent pages',
      priority: 'medium',
    },

    // Site Structure Issues
    {
      id: 'deepPages',
      name: 'Pages Too Deep',
      category: 'siteStructure',
      severity: 'medium',
      description: 'Pages more than 3 clicks from homepage',
      impact: 'Reduces crawl efficiency',
      fix: 'Restructure site to reduce page depth',
      priority: 'medium',
    },
    {
      id: 'orphanPages',
      name: 'Orphan Pages',
      category: 'siteStructure',
      severity: 'medium',
      description: 'Pages with no internal links',
      impact: 'Pages may not be discovered',
      fix: 'Add internal links to orphan pages',
      priority: 'medium',
    },
    {
      id: 'poorNavigation',
      name: 'Poor Navigation',
      category: 'siteStructure',
      severity: 'medium',
      description: 'Confusing or unclear site navigation',
      impact: 'Reduces crawl efficiency',
      fix: 'Improve site navigation structure',
      priority: 'medium',
    },
    {
      id: 'missingBreadcrumbs',
      name: 'Missing Breadcrumbs',
      category: 'siteStructure',
      severity: 'low',
      description: 'No breadcrumb navigation',
      impact: 'Reduces UX and crawl efficiency',
      fix: 'Add breadcrumb navigation',
      priority: 'low',
    },

    // Performance Issues
    {
      id: 'slowPageSpeed',
      name: 'Slow Page Speed',
      category: 'performance',
      severity: 'high',
      description: 'Pages loading slowly',
      impact: 'Affects rankings and user experience',
      fix: 'Optimize images, enable compression, use CDN',
      priority: 'high',
    },
    {
      id: 'largePageSize',
      name: 'Large Page Size',
      category: 'performance',
      severity: 'high',
      description: 'Pages larger than 3MB',
      impact: 'Slow loading, poor UX',
      fix: 'Optimize images and remove unnecessary resources',
      priority: 'high',
    },
    {
      id: 'unoptimizedImages',
      name: 'Unoptimized Images',
      category: 'performance',
      severity: 'high',
      description: 'Images not optimized for web',
      impact: 'Increases page size and load time',
      fix: 'Compress and optimize all images',
      priority: 'high',
    },
    {
      id: 'renderBlockingResources',
      name: 'Render-Blocking Resources',
      category: 'performance',
      severity: 'high',
      description: 'CSS or JS blocking page rendering',
      impact: 'Slows down page load',
      fix: 'Defer non-critical CSS/JS or inline critical CSS',
      priority: 'high',
    },

    // Mobile Usability Issues
    {
      id: 'notMobileFriendly',
      name: 'Not Mobile Friendly',
      category: 'mobileUsability',
      severity: 'critical',
      description: 'Site not optimized for mobile',
      impact: 'Poor mobile rankings',
      fix: 'Implement responsive design',
      priority: 'immediate',
    },
    {
      id: 'smallFontSize',
      name: 'Small Font Size',
      category: 'mobileUsability',
      severity: 'high',
      description: 'Text too small on mobile',
      impact: 'Poor mobile UX',
      fix: 'Increase font size for mobile',
      priority: 'high',
    },
    {
      id: 'clickableElements',
      name: 'Too Close Clickable Elements',
      category: 'mobileUsability',
      severity: 'high',
      description: 'Buttons/links too close together',
      impact: 'Difficult to tap on mobile',
      fix: 'Increase spacing between clickable elements',
      priority: 'high',
    },
    {
      id: 'viewportNotSet',
      name: 'Viewport Not Set',
      category: 'mobileUsability',
      severity: 'high',
      description: 'Missing viewport meta tag',
      impact: 'Page not optimized for mobile',
      fix: 'Add viewport meta tag',
      priority: 'high',
    },

    // Security Issues
    {
      id: 'notHttps',
      name: 'Not Using HTTPS',
      category: 'security',
      severity: 'critical',
      description: 'Site not using HTTPS',
      impact: 'Lower rankings, security warnings',
      fix: 'Implement SSL/TLS certificate',
      priority: 'immediate',
    },
    {
      id: 'mixedContent',
      name: 'Mixed Content',
      category: 'security',
      severity: 'high',
      description: 'HTTPS page loading HTTP resources',
      impact: 'Security warnings, poor UX',
      fix: 'Update all resources to HTTPS',
      priority: 'high',
    },
    {
      id: 'securityHeaders',
      name: 'Missing Security Headers',
      category: 'security',
      severity: 'medium',
      description: 'Missing security headers (CSP, X-Frame-Options)',
      impact: 'Reduced security',
      fix: 'Add security headers to server',
      priority: 'medium',
    },

    // Markup Issues
    {
      id: 'invalidMarkup',
      name: 'Invalid Schema Markup',
      category: 'markup',
      severity: 'medium',
      description: 'Schema markup with errors',
      impact: 'Rich results may not display',
      fix: 'Fix schema markup errors',
      priority: 'medium',
    },
    {
      id: 'missingMarkup',
      name: 'Missing Schema Markup',
      category: 'markup',
      severity: 'low',
      description: 'Pages without schema markup',
      impact: 'May miss rich results',
      fix: 'Add appropriate schema markup',
      priority: 'low',
    },

    // Redirect & URL Issues
    {
      id: 'chainedRedirects',
      name: 'Chained Redirects',
      category: 'redirects',
      severity: 'medium',
      description: 'Multiple redirects in chain',
      impact: 'Wastes crawl budget',
      fix: 'Use direct redirects instead of chains',
      priority: 'medium',
    },
    {
      id: 'brokenRedirects',
      name: 'Broken Redirects',
      category: 'redirects',
      severity: 'high',
      description: 'Redirects to non-existent pages',
      impact: 'Lost traffic and link equity',
      fix: 'Fix redirect destinations',
      priority: 'high',
    },
    {
      id: 'urlParameters',
      name: 'Unnecessary URL Parameters',
      category: 'redirects',
      severity: 'medium',
      description: 'URLs with unnecessary parameters',
      impact: 'Creates duplicate content',
      fix: 'Remove unnecessary parameters or use canonical tags',
      priority: 'medium',
    },
  ],

  // Audit Metrics (15 metrics)
  auditMetrics: [
    {
      id: 'crawlability',
      name: 'Crawlability Score',
      category: 'crawlability',
      description: 'Overall crawlability of the site (0-100)',
      unit: 'score',
      benchmark: { poor: 50, fair: 70, good: 85, excellent: 95 },
    },
    {
      id: 'indexation',
      name: 'Indexation Score',
      category: 'indexation',
      description: 'Overall indexation health (0-100)',
      unit: 'score',
      benchmark: { poor: 50, fair: 70, good: 85, excellent: 95 },
    },
    {
      id: 'siteStructure',
      name: 'Site Structure Score',
      category: 'siteStructure',
      description: 'Quality of site structure (0-100)',
      unit: 'score',
      benchmark: { poor: 50, fair: 70, good: 85, excellent: 95 },
    },
    {
      id: 'performance',
      name: 'Performance Score',
      category: 'performance',
      description: 'Page speed and performance (0-100)',
      unit: 'score',
      benchmark: { poor: 50, fair: 70, good: 85, excellent: 95 },
    },
    {
      id: 'mobileUsability',
      name: 'Mobile Usability Score',
      category: 'mobileUsability',
      description: 'Mobile optimization quality (0-100)',
      unit: 'score',
      benchmark: { poor: 50, fair: 70, good: 85, excellent: 95 },
    },
    {
      id: 'security',
      name: 'Security Score',
      category: 'security',
      description: 'Security implementation (0-100)',
      unit: 'score',
      benchmark: { poor: 50, fair: 70, good: 85, excellent: 95 },
    },
    {
      id: 'markup',
      name: 'Markup Score',
      category: 'markup',
      description: 'Schema markup quality (0-100)',
      unit: 'score',
      benchmark: { poor: 30, fair: 50, good: 70, excellent: 90 },
    },
    {
      id: 'redirects',
      name: 'Redirect Health Score',
      category: 'redirects',
      description: 'Redirect configuration quality (0-100)',
      unit: 'score',
      benchmark: { poor: 50, fair: 70, good: 85, excellent: 95 },
    },
    {
      id: 'totalIssues',
      name: 'Total Issues Found',
      category: 'overall',
      description: 'Total number of issues detected',
      unit: 'count',
      benchmark: { poor: 50, fair: 20, good: 5, excellent: 0 },
    },
    {
      id: 'criticalIssues',
      name: 'Critical Issues',
      category: 'overall',
      description: 'Number of critical severity issues',
      unit: 'count',
      benchmark: { poor: 10, fair: 5, good: 1, excellent: 0 },
    },
    {
      id: 'highIssues',
      name: 'High Priority Issues',
      category: 'overall',
      description: 'Number of high priority issues',
      unit: 'count',
      benchmark: { poor: 20, fair: 10, good: 3, excellent: 0 },
    },
    {
      id: 'crawlBudget',
      name: 'Crawl Budget Efficiency',
      category: 'crawlability',
      description: 'Efficiency of crawl budget usage (0-100)',
      unit: 'percentage',
      benchmark: { poor: 50, fair: 70, good: 85, excellent: 95 },
    },
    {
      id: 'pageSpeed',
      name: 'Average Page Speed',
      category: 'performance',
      description: 'Average page load time in seconds',
      unit: 'seconds',
      benchmark: { poor: 5, fair: 3, good: 2, excellent: 1 },
    },
    {
      id: 'mobileScore',
      name: 'Mobile Lighthouse Score',
      category: 'mobileUsability',
      description: 'Google Lighthouse mobile score (0-100)',
      unit: 'score',
      benchmark: { poor: 50, fair: 70, good: 85, excellent: 95 },
    },
    {
      id: 'desktopScore',
      name: 'Desktop Lighthouse Score',
      category: 'performance',
      description: 'Google Lighthouse desktop score (0-100)',
      unit: 'score',
      benchmark: { poor: 50, fair: 70, good: 85, excellent: 95 },
    },
  ],

  // Audit Reports (6 reports)
  auditReports: [
    {
      id: 'fullAudit',
      name: 'Full Technical Audit',
      description: 'Comprehensive technical SEO audit',
      frequency: 'quarterly',
      sections: ['crawlability', 'indexation', 'siteStructure', 'performance', 'mobileUsability', 'security', 'markup', 'redirects'],
    },
    {
      id: 'crawlabilityAudit',
      name: 'Crawlability Audit',
      description: 'Focused audit on crawlability issues',
      frequency: 'monthly',
      sections: ['crawlability', 'robots.txt', 'sitemap'],
    },
    {
      id: 'performanceAudit',
      name: 'Performance Audit',
      description: 'Focused audit on page speed and performance',
      frequency: 'monthly',
      sections: ['performance', 'pageSpeed', 'coreWebVitals'],
    },
    {
      id: 'mobileAudit',
      name: 'Mobile Usability Audit',
      description: 'Focused audit on mobile optimization',
      frequency: 'monthly',
      sections: ['mobileUsability', 'viewport', 'responsiveness'],
    },
    {
      id: 'securityAudit',
      name: 'Security Audit',
      description: 'Focused audit on security issues',
      frequency: 'monthly',
      sections: ['security', 'https', 'headers'],
    },
    {
      id: 'issueTrackingReport',
      name: 'Issue Tracking Report',
      description: 'Track resolution of identified issues',
      frequency: 'weekly',
      sections: ['openIssues', 'resolvedIssues', 'newIssues'],
    },
  ],

  // Audit Alerts (8 alerts)
  auditAlerts: [
    {
      id: 'criticalIssueFound',
      name: 'Critical Issue Found',
      description: 'Critical severity issue detected',
      severity: 'critical',
      action: 'Immediately investigate and fix',
    },
    {
      id: 'crawlabilityDrop',
      name: 'Crawlability Score Drop',
      description: 'Crawlability score decreased significantly',
      severity: 'warning',
      action: 'Review recent changes and fix issues',
    },
    {
      id: 'performanceDegradation',
      name: 'Performance Degradation',
      description: 'Page speed has decreased',
      severity: 'warning',
      action: 'Optimize images and resources',
    },
    {
      id: 'mobileIssuesDetected',
      name: 'Mobile Issues Detected',
      description: 'Mobile usability issues found',
      severity: 'warning',
      action: 'Test and fix mobile experience',
    },
    {
      id: 'securityIssue',
      name: 'Security Issue Detected',
      description: 'Security vulnerability or misconfiguration',
      severity: 'critical',
      action: 'Immediately address security issue',
    },
    {
      id: 'indexationIssue',
      name: 'Indexation Issue',
      description: 'Pages not being indexed properly',
      severity: 'warning',
      action: 'Review robots.txt and canonical tags',
    },
    {
      id: 'crawlBudgetWaste',
      name: 'Crawl Budget Waste',
      description: 'Crawl budget being wasted on low-value pages',
      severity: 'warning',
      action: 'Optimize site structure and remove low-value pages',
    },
    {
      id: 'brokenLinks',
      name: 'Broken Links Detected',
      description: 'Broken internal or external links found',
      severity: 'warning',
      action: 'Fix or remove broken links',
    },
  ],

  // Best Practices (20+ practices)
  bestPractices: [
    'Ensure all important pages are crawlable and not blocked by robots.txt',
    'Use canonical tags to prevent duplicate content issues',
    'Implement proper redirects (301 for permanent, 302 for temporary)',
    'Optimize page speed - aim for under 2 seconds load time',
    'Implement responsive design for mobile optimization',
    'Use HTTPS on all pages for security',
    'Add security headers (CSP, X-Frame-Options, etc.)',
    'Implement proper schema markup for rich results',
    'Create XML sitemap and submit to search engines',
    'Use descriptive, keyword-rich URLs',
    'Optimize images for web (compress, use modern formats)',
    'Minimize render-blocking resources',
    'Enable gzip compression on server',
    'Use a CDN for faster content delivery',
    'Implement lazy loading for images',
    'Set proper viewport meta tag for mobile',
    'Use descriptive heading hierarchy (H1, H2, H3)',
    'Avoid excessive internal linking',
    'Monitor crawl errors in Google Search Console',
    'Test site with Google Mobile-Friendly Test',
    'Use Google PageSpeed Insights for optimization tips',
    'Implement breadcrumb navigation',
    'Use structured data markup (JSON-LD)',
    'Avoid keyword stuffing and over-optimization',
    'Keep site structure shallow (3 clicks from homepage)',
  ],

  // Audit Checklist (5 categories)
  auditChecklist: [
    {
      category: 'Pre-Audit',
      items: [
        'Define audit scope and objectives',
        'Gather baseline metrics',
        'Document current issues',
        'Set up monitoring tools',
        'Create audit timeline',
      ],
    },
    {
      category: 'Crawlability Audit',
      items: [
        'Check robots.txt configuration',
        'Verify sitemap.xml exists and is valid',
        'Test for crawl errors',
        'Check for noindex tags',
        'Verify blocking resources',
      ],
    },
    {
      category: 'Performance Audit',
      items: [
        'Test page speed with PageSpeed Insights',
        'Check Core Web Vitals',
        'Analyze image optimization',
        'Review render-blocking resources',
        'Test with Lighthouse',
      ],
    },
    {
      category: 'Mobile & Security Audit',
      items: [
        'Test mobile-friendliness',
        'Verify HTTPS implementation',
        'Check security headers',
        'Test viewport configuration',
        'Verify clickable element spacing',
      ],
    },
    {
      category: 'Post-Audit',
      items: [
        'Prioritize issues by severity',
        'Create action plan',
        'Assign responsibilities',
        'Set timelines for fixes',
        'Schedule follow-up audit',
      ],
    },
  ],

  // Audit Severity Levels
  severityLevels: [
    {
      level: 'critical',
      score: 0,
      description: 'Prevents crawling or indexation',
      action: 'Fix immediately',
      timeframe: '1-2 days',
    },
    {
      level: 'high',
      score: 25,
      description: 'Significantly impacts SEO',
      action: 'Fix within 1 week',
      timeframe: '3-7 days',
    },
    {
      level: 'medium',
      score: 50,
      description: 'Moderately impacts SEO',
      action: 'Fix within 2 weeks',
      timeframe: '1-2 weeks',
    },
    {
      level: 'low',
      score: 75,
      description: 'Minor impact on SEO',
      action: 'Fix when possible',
      timeframe: '2-4 weeks',
    },
  ],

  // Audit Process (8 steps)
  auditProcess: [
    {
      step: 1,
      name: 'Scope Definition',
      description: 'Define audit scope and objectives',
      duration: '1-2 hours',
      tools: ['Spreadsheet', 'Project management tool'],
    },
    {
      step: 2,
      name: 'Baseline Assessment',
      description: 'Gather current metrics and baseline data',
      duration: '2-4 hours',
      tools: ['Google Search Console', 'PageSpeed Insights', 'Lighthouse'],
    },
    {
      step: 3,
      name: 'Crawlability Testing',
      description: 'Test crawlability and indexation',
      duration: '4-8 hours',
      tools: ['Screaming Frog', 'Google Search Console', 'robots.txt tester'],
    },
    {
      step: 4,
      name: 'Performance Analysis',
      description: 'Analyze page speed and performance',
      duration: '4-8 hours',
      tools: ['PageSpeed Insights', 'Lighthouse', 'WebPageTest'],
    },
    {
      step: 5,
      name: 'Mobile & Security Review',
      description: 'Review mobile optimization and security',
      duration: '4-6 hours',
      tools: ['Mobile-Friendly Test', 'SSL checker', 'Security headers'],
    },
    {
      step: 6,
      name: 'Issue Compilation',
      description: 'Compile all issues and prioritize',
      duration: '2-4 hours',
      tools: ['Spreadsheet', 'Issue tracking tool'],
    },
    {
      step: 7,
      name: 'Recommendations',
      description: 'Create action plan and recommendations',
      duration: '2-4 hours',
      tools: ['Documentation tool', 'Project management'],
    },
    {
      step: 8,
      name: 'Reporting',
      description: 'Create comprehensive audit report',
      duration: '2-4 hours',
      tools: ['Report template', 'Visualization tools'],
    },
  ],
};

export default technicalSeoAuditConfig;
